image: java:latest

stages:
  - build
  - execute
  
build:
  stage: build
  script: /usr/lib/jvm/jdk-13.0.1/bin/javac HelloWorld.java
  artifacts:
    paths: 
      - HelloWorld.*

execute:
  stage: execute
  script: /usr/lib/jvm/jdk-13.0.1/bin/java HelloWorld
  